# Generated by Django 3.2.3 on 2021-07-06 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('overview', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_1', models.ImageField(blank=True, default='', upload_to='')),
                ('image_2', models.ImageField(blank=True, default='', upload_to='')),
                ('image_3', models.ImageField(blank=True, default='', upload_to='')),
                ('colors', models.CharField(choices=[('G', 'Green'), ('B', 'Blue'), ('Gr', 'Gray'), ('Y', 'Yellow'), ('R', 'Red')], default='Green', max_length=2)),
                ('categories', models.CharField(choices=[('BS', 'BLUCHER SHOE'), ('CS', 'CLOG SHOE'), ('SBS', 'SNOW BOOT SHOE'), ('GS', 'GALESH SHOE'), ('PS', 'PATAUGAS SHOE'), ('JS', 'JAZZ SHOE')], default='BLUCHER SHOE', max_length=3)),
                ('sizes', models.CharField(choices=[('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5')], default='5.5', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
