# Generated by Django 3.2.3 on 2021-07-09 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
