# Generated by Django 3.2.5 on 2021-07-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210728_0313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
