# Generated by Django 3.2.5 on 2021-07-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(choices=[('Green', 'Green'), ('Blue', 'Blue'), ('Gray', 'Gray'), ('Yellow', 'Yellow'), ('Red', 'Red')], max_length=12),
        ),
    ]
