# Generated by Django 3.2.5 on 2021-07-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
    ]
